[frontend]
server1 ansible_host="localhost"  ansible_port="22" #var=<value> 
server2 ansible_host="localhost" 
server3 ansible_host="localhost" 
server4 ansible_host="localhost" 
server5 ansible_host="localhost" 
server6 ansible_host="localhost" 
server7 ansible_host="localhost" 

[backend]
server10 ansible_host="localhost"

[backend:children]
frontend

[frontend:vars]
ansible_python_interpreter="/usr/bin/python"
ansible_user="devarshi_balu"
ansible_password="devarshi"
ansible_become="yes"
ansible_shell_executable="/usr/bin/bash"