- name: play-1 
  hosts:  localhost
  connection: local
  # become: yes 
  vars:
    isLive: yes  #yaml parses it as true
    # version: "1.1000" # 
    comment: "Hello world This is YAML FILE"
    ip: "126.90.89.2000000"
  tasks: 
    - name: task-1
      ansible.builtin.package: 
        name: zip
        state: present
        register: register_package
    
      ansible.builtin.debug: 
        msg:
          port: "{{port | default('20')}}"
          version: "{{version | default('10.10.1000')}}"
          comment_upper: "{{ comment | upper }}"
          comment_lower: "{{ comment | lower }}"
          comment_capitalize: "{{ comment | capitalize }}"
          ip_address: "{{ ip | ansible.builtin.ipv4 }}"
          register_package: register_package