all: 
  children: 
    production: 
      children:
        web: 
          hosts: 
            web1: 
              ansible_host: 127.0.0.1
            web2: 
              ansible_host: 127.0.0.1
            web3: 
              ansible_host: 127.0.0.1
            web4: 
              ansible_host: 127.0.0.1
        db: 
          hosts: 
            db1: 
              ansible_host: 127.0.0.1
            db2: 
              ansible_host: 127.0.0.1
            db3: 
              ansible_host: 127.0.0.1
            db4: 
              ansible_host: 127.0.0.1